services:
    postgres:
        image: 'postgres:latest'
        container_name: 'nttbank-postgres'
        environment:
            - 'POSTGRES_DB=nttbank'
            - 'POSTGRES_PASSWORD=nttbank'
            - 'POSTGRES_USER=nttbank'
        ports:
            - '5432:5432'
        volumes:
            - 'postgres_data:/var/lib/postgresql/data'
volumes:
    postgres_data:
networks:
    springboot-network:
        driver: bridge
